# Generated by Django 3.1 on 2020-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='banner/')),
            ],
        ),
    ]
