# Generated by Django 3.1 on 2020-10-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0003_first_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='First_Banner',
        ),
    ]
