# Generated by Django 3.1 on 2020-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0005_firstbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='courses/')),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=500)),
                ('Duration', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=122)),
                ('module', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
