# Generated by Django 3.1 on 2020-10-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0008_auto_20201007_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bigImage',
            field=models.ImageField(default='', upload_to='courses/'),
        ),
    ]
