# Generated by Django 3.1 on 2020-10-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0009_course_bigimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
