# Generated by Django 3.1 on 2020-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0015_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
