# Generated by Django 3.1 on 2020-10-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenlab', '0018_auto_20201028_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
